icon-speech-streamline-talk-user:
  text: >
    ###### **Visioning**

    Let us get to know you and we’ll strategize what a website can do for your organization. Email us at info@bigriverwebdesign.com to set up a phone consultation to find the right tactics, tools, and platforms for you.
icon-pen-streamline:
  text: >
    ###### **Content Generation**

    Our team works with professional photographers, videographers, writers, and editors to create whatever content you made need to communicate your mission to your people.
icon-child:
  text: >
    ###### **Personal Websites**

    Looking to get a site up as quickly and affordably as possible?  We use tools like Squarespace, WordPress, and Weebly to build out sites for a hard to beat price starting at $600.
icon-paint-brush:
  text: >
    ###### **Custom Design and Development**

    For larger websites, our designers work with clients to develop an aesthetic that meets the organizations goals and our developers work to make that vision a reality.

icon-design-graphic-tablet-streamline-tablet:
  text: >
    ###### **Advanced Development and App Development**

    Looking for advanced functionality on your website or looking to develop a mobile application?  Our developers are deeply knowledgable about a wide array of platforms that allow us to build out advanced features to meet our client's specific needs.
    
icon-computer-network-streamline:
  text: >
    ###### **Website Hosting and Maintenance**

    Our website hosting package means that you don’t have to worry about dealing with another hosting company because we take care of it for you. Our WordPress maintenance package keeps sites updated, backed up, and checks them for malware on a regular basis. For more information, contact us at info@bigriverwebdesign.com
